

function [M, C, G, Q] = Lagrangian8dof_1Segment()
% Lagrangian8dof   Derive and solve the Lagrange Equation of a discretised
% 8DOF Lumped mass model of a 1-segment continuum robot
% Returns the solved M, C, G, Q matrices
   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 8-link 1-Segment planar robot dynamics %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    %% computation parameters
    n = 8; %state vector length

    fprintf('Variables...')
    %% model state 
    
    
    syms('theta',[n 1])
    syms('dot_theta',[n 1])
    syms('ddot_theta',[n 1])
    

    %% model parameters
    syms m l r k lambda f1 f2;

    %% external
    syms tau1 tau2;
    fprintf(' done\n')

    %% equations and lagrangian

    fprintf('Lagrangian...')
    
    x1 = - l*sin(theta1);
    x2 = x1 - l*sin(theta1) - l*sin(theta1+theta2);
    x3 = x2 - l*sin(theta1+theta2) - l*sin(theta1+theta2+theta3);
    x4 = x3 - l*sin(theta1+theta2+theta3) - l*sin(theta1+theta2+theta3+theta4);
    x5 = x4 - l*sin(theta1+theta2+theta3+theta4) - l*sin(theta1+theta2+theta3+theta4+theta5);
    x6 = x5 - l*sin(theta1+theta2+theta3+theta4+theta5) - l*sin(theta1+theta2+theta3+theta4+theta5+theta6);
    x7 = x6 - l*sin(theta1+theta2+theta3+theta4+theta5+theta6) - l*sin(theta1+theta2+theta3+theta4+theta5+theta6+theta7);
    x8 = x7 - l*sin(theta1+theta2+theta3+theta4+theta5+theta6+theta7) - l*sin(theta1+theta2+theta3+theta4+theta5+theta6+theta7+theta8);
    
    y1 = l + l*cos(theta1);
    y2 = y1 + l*cos(theta1) + l*cos(theta1+theta2);
    y3 = y2 + l*cos(theta1+theta2) + l*cos(theta1+theta2+theta3);
    y4 = y3 + l*cos(theta1+theta2+theta3) + l*cos(theta1+theta2+theta3+theta4);
    y5 = y4 + l*cos(theta1+theta2+theta3+theta4) + l*cos(theta1+theta2+theta3+theta4+theta5);
    y6 = y5 + l*cos(theta1+theta2+theta3+theta4+theta5) + l*cos(theta1+theta2+theta3+theta4+theta5+theta6);
    y7 = y6 + l*cos(theta1+theta2+theta3+theta4+theta5+theta6) + l*cos(theta1+theta2+theta3+theta4+theta5+theta6+theta7);
    y8 = y7 + l*cos(theta1+theta2+theta3+theta4+theta5+theta6+theta7) + l*cos(theta1+theta2+theta3+theta4+theta5+theta6+theta7+theta8);
    
    dot_x1 = diff(x1,theta1)*dot_theta1 + diff(x1,theta2)*dot_theta2 + diff(x1,theta3)*dot_theta3 + diff(x1,theta4)*dot_theta4 + diff(x1,theta5)*dot_theta5 + diff(x1,theta6)*dot_theta6 + diff(x1,theta7)*dot_theta7 + diff(x1,theta8)*dot_theta8;
    dot_y1 = diff(y1,theta1)*dot_theta1 + diff(y1,theta2)*dot_theta2 + diff(y1,theta3)*dot_theta3 + diff(y1,theta4)*dot_theta4 + diff(y1,theta5)*dot_theta5 + diff(y1,theta6)*dot_theta6 + diff(y1,theta7)*dot_theta7 + diff(y1,theta8)*dot_theta8;
    dot_x2 = diff(x2,theta1)*dot_theta1 + diff(x2,theta2)*dot_theta2 + diff(x2,theta3)*dot_theta3 + diff(x2,theta4)*dot_theta4 + diff(x2,theta5)*dot_theta5 + diff(x2,theta6)*dot_theta6 + diff(x2,theta7)*dot_theta7 + diff(x2,theta8)*dot_theta8;
    dot_y2 = diff(y2,theta1)*dot_theta1 + diff(y2,theta2)*dot_theta2 + diff(y2,theta3)*dot_theta3 + diff(y2,theta4)*dot_theta4 + diff(y2,theta5)*dot_theta5 + diff(y2,theta6)*dot_theta6 + diff(y2,theta7)*dot_theta7 + diff(y2,theta8)*dot_theta8;
    dot_x3 = diff(x3,theta1)*dot_theta1 + diff(x3,theta2)*dot_theta2 + diff(x3,theta3)*dot_theta3 + diff(x3,theta4)*dot_theta4 + diff(x3,theta5)*dot_theta5 + diff(x3,theta6)*dot_theta6 + diff(x3,theta7)*dot_theta7 + diff(x3,theta8)*dot_theta8;
    dot_y3 = diff(y3,theta1)*dot_theta1 + diff(y3,theta2)*dot_theta2 + diff(y3,theta3)*dot_theta3 + diff(y3,theta4)*dot_theta4 + diff(y3,theta5)*dot_theta5 + diff(y3,theta6)*dot_theta6 + diff(y3,theta7)*dot_theta7 + diff(y3,theta8)*dot_theta8;
    dot_x4 = diff(x4,theta1)*dot_theta1 + diff(x4,theta2)*dot_theta2 + diff(x4,theta3)*dot_theta3 + diff(x4,theta4)*dot_theta4 + diff(x4,theta5)*dot_theta5 + diff(x4,theta6)*dot_theta6 + diff(x4,theta7)*dot_theta7 + diff(x4,theta8)*dot_theta8;
    dot_y4 = diff(y4,theta1)*dot_theta1 + diff(y4,theta2)*dot_theta2 + diff(y4,theta3)*dot_theta3 + diff(y4,theta4)*dot_theta4 + diff(y4,theta5)*dot_theta5 + diff(y4,theta6)*dot_theta6 + diff(y4,theta7)*dot_theta7 + diff(y4,theta8)*dot_theta8;
    dot_x5 = diff(x5,theta1)*dot_theta1 + diff(x5,theta2)*dot_theta2 + diff(x5,theta3)*dot_theta3 + diff(x5,theta4)*dot_theta4 + diff(x5,theta5)*dot_theta5 + diff(x5,theta6)*dot_theta6 + diff(x5,theta7)*dot_theta7 + diff(x5,theta8)*dot_theta8;
    dot_y5 = diff(y5,theta1)*dot_theta1 + diff(y5,theta2)*dot_theta2 + diff(y5,theta3)*dot_theta3 + diff(y5,theta4)*dot_theta4 + diff(y5,theta5)*dot_theta5 + diff(y5,theta6)*dot_theta6 + diff(y5,theta7)*dot_theta7 + diff(y5,theta8)*dot_theta8;
    dot_x6 = diff(x6,theta1)*dot_theta1 + diff(x6,theta2)*dot_theta2 + diff(x6,theta3)*dot_theta3 + diff(x6,theta4)*dot_theta4 + diff(x6,theta5)*dot_theta5 + diff(x6,theta6)*dot_theta6 + diff(x6,theta7)*dot_theta7 + diff(x6,theta8)*dot_theta8;
    dot_y6 = diff(y6,theta1)*dot_theta1 + diff(y6,theta2)*dot_theta2 + diff(y6,theta3)*dot_theta3 + diff(y6,theta4)*dot_theta4 + diff(y6,theta5)*dot_theta5 + diff(y6,theta6)*dot_theta6 + diff(y6,theta7)*dot_theta7 + diff(y6,theta8)*dot_theta8;
    dot_x7 = diff(x7,theta1)*dot_theta1 + diff(x7,theta2)*dot_theta2 + diff(x7,theta3)*dot_theta3 + diff(x7,theta4)*dot_theta4 + diff(x7,theta5)*dot_theta5 + diff(x7,theta6)*dot_theta6 + diff(x7,theta7)*dot_theta7 + diff(x7,theta8)*dot_theta8;
    dot_y7 = diff(y7,theta1)*dot_theta1 + diff(y7,theta2)*dot_theta2 + diff(y7,theta3)*dot_theta3 + diff(y7,theta4)*dot_theta4 + diff(y7,theta5)*dot_theta5 + diff(y7,theta6)*dot_theta6 + diff(y7,theta7)*dot_theta7 + diff(y7,theta8)*dot_theta8;
    dot_x8 = diff(x8,theta1)*dot_theta1 + diff(x8,theta2)*dot_theta2 + diff(x8,theta3)*dot_theta3 + diff(x8,theta4)*dot_theta4 + diff(x8,theta5)*dot_theta5 + diff(x8,theta6)*dot_theta6 + diff(x8,theta7)*dot_theta7 + diff(x8,theta8)*dot_theta8;
    dot_y8 = diff(y8,theta1)*dot_theta1 + diff(y8,theta2)*dot_theta2 + diff(y8,theta3)*dot_theta3 + diff(y8,theta4)*dot_theta4 + diff(y8,theta5)*dot_theta5 + diff(y8,theta6)*dot_theta6 + diff(y8,theta7)*dot_theta7 + diff(y8,theta8)*dot_theta8;
    
    U = 1/2*k*(theta1^2 + theta2^2 + theta3^2 + theta4^2+ theta5^2 + theta6^2 + theta7^2 + theta8^2);
    P = 1/2*lambda*(dot_theta1^2 + dot_theta2^2 + dot_theta3^2 + dot_theta4^2 + dot_theta5^2 + dot_theta6^2 + dot_theta7^2 + dot_theta8^2);
    T = 1/2*m*(dot_x1^2 + dot_y1^2) + 1/2*m*(dot_x2^2 + dot_y2^2) + 1/2*m*(dot_x3^2 + dot_y3^2) + 1/2*m*(dot_x4^2 + dot_y4^2) + 1/2*m*(dot_x5^2 + dot_y5^2) + 1/2*m*(dot_x6^2 + dot_y6^2) + 1/2*m*(dot_x7^2 + dot_y7^2) + 1/2*m*(dot_x8^2 + dot_y8^2);
    L = T-U;
    fprintf(' done\n')

    fprintf('dL/dtheta...')
    L_theta1 = diff(L,theta1);
    L_theta2 = diff(L,theta2);
    L_theta3 = diff(L,theta3);
    L_theta4 = diff(L,theta4);
    L_theta5 = diff(L,theta5);
    L_theta6 = diff(L,theta6);
    L_theta7 = diff(L,theta7);
    L_theta8 = diff(L,theta8);
    fprintf(' done\n')

    fprintf('dL/dtheta...')
    P_theta1 = diff(P,dot_theta1);
    P_theta2 = diff(P,dot_theta2);
    P_theta3 = diff(P,dot_theta3);
    P_theta4 = diff(P,dot_theta4);
    P_theta5 = diff(P,dot_theta5);
    P_theta6 = diff(P,dot_theta6);
    P_theta7 = diff(P,dot_theta7);
    P_theta8 = diff(P,dot_theta8);
    fprintf(' done\n')

    fprintf('d/dt (dL/dot_theta)...') 
    L_dot_theta1 = diff(L,dot_theta1);
    L_dot_theta2 = diff(L,dot_theta2);
    L_dot_theta3 = diff(L,dot_theta3);
    L_dot_theta4 = diff(L,dot_theta4);
    L_dot_theta5 = diff(L,dot_theta5);
    L_dot_theta6 = diff(L,dot_theta6);
    L_dot_theta7 = diff(L,dot_theta7);
    L_dot_theta8 = diff(L,dot_theta8);

    dL_dot_theta1_dt =  diff(L_dot_theta1,theta1)*dot_theta1 + ...
                        + diff(L_dot_theta1,theta2)*dot_theta2 + ...
                        + diff(L_dot_theta1,theta3)*dot_theta3 + ...
                        + diff(L_dot_theta1,theta4)*dot_theta4 + ...
                        + diff(L_dot_theta1,theta5)*dot_theta5 + ...
                        + diff(L_dot_theta1,theta6)*dot_theta6 + ...
                        + diff(L_dot_theta1,theta7)*dot_theta7 + ...
                        + diff(L_dot_theta1,theta8)*dot_theta8 + ...
                        + diff(L_dot_theta1,dot_theta1)*ddot_theta1 + ...
                        + diff(L_dot_theta1,dot_theta2)*ddot_theta2 + ...
                        + diff(L_dot_theta1,dot_theta3)*ddot_theta3 + ...
                        + diff(L_dot_theta1,dot_theta4)*ddot_theta4 + ...
                        + diff(L_dot_theta1,dot_theta5)*ddot_theta5 + ...
                        + diff(L_dot_theta1,dot_theta6)*ddot_theta6 + ...
                        + diff(L_dot_theta1,dot_theta7)*ddot_theta7 + ...
                        + diff(L_dot_theta1,dot_theta8)*ddot_theta8;
    dL_dot_theta2_dt =  diff(L_dot_theta2,theta1)*dot_theta1 + ...
                        + diff(L_dot_theta2,theta2)*dot_theta2 + ...
                        + diff(L_dot_theta2,theta3)*dot_theta3 + ...
                        + diff(L_dot_theta2,theta4)*dot_theta4 + ...
                        + diff(L_dot_theta2,theta5)*dot_theta5 + ...
                        + diff(L_dot_theta2,theta6)*dot_theta6 + ...
                        + diff(L_dot_theta2,theta7)*dot_theta7 + ...
                        + diff(L_dot_theta2,theta8)*dot_theta8 + ...
                        + diff(L_dot_theta2,dot_theta1)*ddot_theta1 + ...
                        + diff(L_dot_theta2,dot_theta2)*ddot_theta2 + ...
                        + diff(L_dot_theta2,dot_theta3)*ddot_theta3 + ...
                        + diff(L_dot_theta2,dot_theta4)*ddot_theta4 + ...
                        + diff(L_dot_theta2,dot_theta5)*ddot_theta5 + ...
                        + diff(L_dot_theta2,dot_theta6)*ddot_theta6 + ...
                        + diff(L_dot_theta2,dot_theta7)*ddot_theta7 + ...
                        + diff(L_dot_theta2,dot_theta8)*ddot_theta8;
    dL_dot_theta3_dt =  diff(L_dot_theta3,theta1)*dot_theta1 + ...
                        + diff(L_dot_theta3,theta2)*dot_theta2 + ...
                        + diff(L_dot_theta3,theta3)*dot_theta3 + ...
                        + diff(L_dot_theta3,theta4)*dot_theta4 + ...
                        + diff(L_dot_theta3,theta5)*dot_theta5 + ...
                        + diff(L_dot_theta3,theta6)*dot_theta6 + ...
                        + diff(L_dot_theta3,theta7)*dot_theta7 + ...
                        + diff(L_dot_theta3,theta8)*dot_theta8 + ...
                        + diff(L_dot_theta3,dot_theta1)*ddot_theta1 + ...
                        + diff(L_dot_theta3,dot_theta2)*ddot_theta2 + ...
                        + diff(L_dot_theta3,dot_theta3)*ddot_theta3 + ...
                        + diff(L_dot_theta3,dot_theta4)*ddot_theta4 + ...
                        + diff(L_dot_theta3,dot_theta5)*ddot_theta5 + ...
                        + diff(L_dot_theta3,dot_theta6)*ddot_theta6 + ...
                        + diff(L_dot_theta3,dot_theta7)*ddot_theta7 + ...
                        + diff(L_dot_theta3,dot_theta8)*ddot_theta8;
    dL_dot_theta4_dt =  diff(L_dot_theta4,theta1)*dot_theta1 + ...
                        + diff(L_dot_theta4,theta2)*dot_theta2 + ...
                        + diff(L_dot_theta4,theta3)*dot_theta3 + ...
                        + diff(L_dot_theta4,theta4)*dot_theta4 + ...
                        + diff(L_dot_theta4,theta5)*dot_theta5 + ...
                        + diff(L_dot_theta4,theta6)*dot_theta6 + ...
                        + diff(L_dot_theta4,theta7)*dot_theta7 + ...
                        + diff(L_dot_theta4,theta8)*dot_theta8 + ...
                        + diff(L_dot_theta4,dot_theta1)*ddot_theta1 + ...
                        + diff(L_dot_theta4,dot_theta2)*ddot_theta2 + ...
                        + diff(L_dot_theta4,dot_theta3)*ddot_theta3 + ...
                        + diff(L_dot_theta4,dot_theta4)*ddot_theta4 + ...
                        + diff(L_dot_theta4,dot_theta5)*ddot_theta5 + ...
                        + diff(L_dot_theta4,dot_theta6)*ddot_theta6 + ...
                        + diff(L_dot_theta4,dot_theta7)*ddot_theta7 + ...
                        + diff(L_dot_theta4,dot_theta8)*ddot_theta8;
    dL_dot_theta5_dt =  diff(L_dot_theta5,theta1)*dot_theta1 + ...
                        + diff(L_dot_theta5,theta2)*dot_theta2 + ...
                        + diff(L_dot_theta5,theta3)*dot_theta3 + ...
                        + diff(L_dot_theta5,theta4)*dot_theta4 + ...
                        + diff(L_dot_theta5,theta5)*dot_theta5 + ...
                        + diff(L_dot_theta5,theta6)*dot_theta6 + ...
                        + diff(L_dot_theta5,theta7)*dot_theta7 + ...
                        + diff(L_dot_theta5,theta8)*dot_theta8 + ...
                        + diff(L_dot_theta5,dot_theta1)*ddot_theta1 + ...
                        + diff(L_dot_theta5,dot_theta2)*ddot_theta2 + ...
                        + diff(L_dot_theta5,dot_theta3)*ddot_theta3 + ...
                        + diff(L_dot_theta5,dot_theta4)*ddot_theta4 + ...
                        + diff(L_dot_theta5,dot_theta5)*ddot_theta5 + ...
                        + diff(L_dot_theta5,dot_theta6)*ddot_theta6 + ...
                        + diff(L_dot_theta5,dot_theta7)*ddot_theta7 + ...
                        + diff(L_dot_theta5,dot_theta8)*ddot_theta8;
    dL_dot_theta6_dt =  diff(L_dot_theta6,theta1)*dot_theta1 + ...
                        + diff(L_dot_theta6,theta2)*dot_theta2 + ...
                        + diff(L_dot_theta6,theta3)*dot_theta3 + ...
                        + diff(L_dot_theta6,theta4)*dot_theta4 + ...
                        + diff(L_dot_theta6,theta5)*dot_theta5 + ...
                        + diff(L_dot_theta6,theta6)*dot_theta6 + ...
                        + diff(L_dot_theta6,theta7)*dot_theta7 + ...
                        + diff(L_dot_theta6,theta8)*dot_theta8 + ...
                        + diff(L_dot_theta6,dot_theta1)*ddot_theta1 + ...
                        + diff(L_dot_theta6,dot_theta2)*ddot_theta2 + ...
                        + diff(L_dot_theta6,dot_theta3)*ddot_theta3 + ...
                        + diff(L_dot_theta6,dot_theta4)*ddot_theta4 + ...
                        + diff(L_dot_theta6,dot_theta5)*ddot_theta5 + ...
                        + diff(L_dot_theta6,dot_theta6)*ddot_theta6 + ...
                        + diff(L_dot_theta6,dot_theta7)*ddot_theta7 + ...
                        + diff(L_dot_theta6,dot_theta8)*ddot_theta8;
    dL_dot_theta7_dt =  diff(L_dot_theta7,theta1)*dot_theta1 + ...
                        + diff(L_dot_theta7,theta2)*dot_theta2 + ...
                        + diff(L_dot_theta7,theta3)*dot_theta3 + ...
                        + diff(L_dot_theta7,theta4)*dot_theta4 + ...
                        + diff(L_dot_theta7,theta5)*dot_theta5 + ...
                        + diff(L_dot_theta7,theta6)*dot_theta6 + ...
                        + diff(L_dot_theta7,theta7)*dot_theta7 + ...
                        + diff(L_dot_theta7,theta8)*dot_theta8 + ...
                        + diff(L_dot_theta7,dot_theta1)*ddot_theta1 + ...
                        + diff(L_dot_theta7,dot_theta2)*ddot_theta2 + ...
                        + diff(L_dot_theta7,dot_theta3)*ddot_theta3 + ...
                        + diff(L_dot_theta7,dot_theta4)*ddot_theta4 + ...
                        + diff(L_dot_theta7,dot_theta5)*ddot_theta5 + ...
                        + diff(L_dot_theta7,dot_theta6)*ddot_theta6 + ...
                        + diff(L_dot_theta7,dot_theta7)*ddot_theta7 + ...
                        + diff(L_dot_theta7,dot_theta8)*ddot_theta8;
    dL_dot_theta8_dt =  diff(L_dot_theta8,theta1)*dot_theta1 + ...
                        + diff(L_dot_theta8,theta2)*dot_theta2 + ...
                        + diff(L_dot_theta8,theta3)*dot_theta3 + ...
                        + diff(L_dot_theta8,theta4)*dot_theta4 + ...
                        + diff(L_dot_theta8,theta5)*dot_theta5 + ...
                        + diff(L_dot_theta8,theta6)*dot_theta6 + ...
                        + diff(L_dot_theta8,theta7)*dot_theta7 + ...
                        + diff(L_dot_theta8,theta8)*dot_theta8 + ...
                        + diff(L_dot_theta8,dot_theta1)*ddot_theta1 + ...
                        + diff(L_dot_theta8,dot_theta2)*ddot_theta2 + ...
                        + diff(L_dot_theta8,dot_theta3)*ddot_theta3 + ...
                        + diff(L_dot_theta8,dot_theta4)*ddot_theta4 + ...
                        + diff(L_dot_theta8,dot_theta5)*ddot_theta5 + ...
                        + diff(L_dot_theta8,dot_theta6)*ddot_theta6 + ...
                        + diff(L_dot_theta8,dot_theta7)*ddot_theta7 + ...
                        + diff(L_dot_theta8,dot_theta8)*ddot_theta8;
    fprintf(' done\n\n')               

    disp('Dynamics:C')
    eq1 = simplify(dL_dot_theta1_dt - L_theta1 + P_theta1,'Steps',2) ;
    eq2 = simplify(dL_dot_theta2_dt - L_theta2 + P_theta2,'Steps',2) ;
    eq3 = simplify(dL_dot_theta3_dt - L_theta3 + P_theta3,'Steps',2) ;
    eq4 = simplify(dL_dot_theta4_dt - L_theta4 + P_theta4,'Steps',2) ;
    eq5 = simplify(dL_dot_theta5_dt - L_theta5 + P_theta5,'Steps',2) ;
    eq6 = simplify(dL_dot_theta6_dt - L_theta6 + P_theta6,'Steps',2) ;
    eq7 = simplify(dL_dot_theta7_dt - L_theta7 + P_theta7,'Steps',2) ;
    eq8 = simplify(dL_dot_theta8_dt - L_theta8 + P_theta8,'Steps',2) ;
    
    M = [diff(eq1,ddot_theta1), diff(eq1,ddot_theta2), diff(eq1,ddot_theta3), diff(eq1,ddot_theta4), diff(eq1,ddot_theta5), diff(eq1,ddot_theta6), diff(eq1,ddot_theta7), diff(eq1,ddot_theta8); ...
         diff(eq2,ddot_theta1), diff(eq2,ddot_theta2), diff(eq2,ddot_theta3), diff(eq2,ddot_theta4), diff(eq2,ddot_theta5), diff(eq2,ddot_theta6), diff(eq2,ddot_theta7), diff(eq2,ddot_theta8); ...
         diff(eq3,ddot_theta1), diff(eq3,ddot_theta2), diff(eq3,ddot_theta3), diff(eq3,ddot_theta4), diff(eq3,ddot_theta5), diff(eq3,ddot_theta6), diff(eq3,ddot_theta7), diff(eq3,ddot_theta8); ...
         diff(eq4,ddot_theta1), diff(eq4,ddot_theta2), diff(eq4,ddot_theta3), diff(eq4,ddot_theta4), diff(eq4,ddot_theta5), diff(eq4,ddot_theta6), diff(eq4,ddot_theta7), diff(eq4,ddot_theta8); ...
         diff(eq5,ddot_theta1), diff(eq5,ddot_theta2), diff(eq5,ddot_theta3), diff(eq5,ddot_theta4), diff(eq5,ddot_theta5), diff(eq5,ddot_theta6), diff(eq5,ddot_theta7), diff(eq5,ddot_theta8); ...
         diff(eq6,ddot_theta1), diff(eq6,ddot_theta2), diff(eq6,ddot_theta3), diff(eq6,ddot_theta4), diff(eq6,ddot_theta5), diff(eq6,ddot_theta6), diff(eq6,ddot_theta7), diff(eq6,ddot_theta8); ...
         diff(eq7,ddot_theta1), diff(eq7,ddot_theta2), diff(eq7,ddot_theta3), diff(eq7,ddot_theta4), diff(eq7,ddot_theta5), diff(eq7,ddot_theta6), diff(eq7,ddot_theta7), diff(eq7,ddot_theta8); ...
         diff(eq8,ddot_theta1), diff(eq8,ddot_theta2), diff(eq8,ddot_theta3), diff(eq8,ddot_theta4), diff(eq8,ddot_theta5), diff(eq8,ddot_theta6), diff(eq8,ddot_theta7), diff(eq8,ddot_theta8); ...
         ];
    disp('Dynamics:M done')
    C1 = simplify(eq1 - subs(eq1, [dot_theta1, dot_theta2, dot_theta3, dot_theta4, dot_theta5, dot_theta6, dot_theta7, dot_theta8],[0,0,0,0,0,0,0,0]));
    C2 = simplify(eq2 - subs(eq2, [dot_theta1, dot_theta2, dot_theta3, dot_theta4, dot_theta5, dot_theta6, dot_theta7, dot_theta8],[0,0,0,0,0,0,0,0]));
    C3 = simplify(eq3 - subs(eq3, [dot_theta1, dot_theta2, dot_theta3, dot_theta4, dot_theta5, dot_theta6, dot_theta7, dot_theta8],[0,0,0,0,0,0,0,0]));
    C4 = simplify(eq4 - subs(eq4, [dot_theta1, dot_theta2, dot_theta3, dot_theta4, dot_theta5, dot_theta6, dot_theta7, dot_theta8],[0,0,0,0,0,0,0,0]));
    C5 = simplify(eq5 - subs(eq5, [dot_theta1, dot_theta2, dot_theta3, dot_theta4, dot_theta5, dot_theta6, dot_theta7, dot_theta8],[0,0,0,0,0,0,0,0]));
    C6 = simplify(eq6 - subs(eq6, [dot_theta1, dot_theta2, dot_theta3, dot_theta4, dot_theta5, dot_theta6, dot_theta7, dot_theta8],[0,0,0,0,0,0,0,0]));
    C7 = simplify(eq7 - subs(eq7, [dot_theta1, dot_theta2, dot_theta3, dot_theta4, dot_theta5, dot_theta6, dot_theta7, dot_theta8],[0,0,0,0,0,0,0,0]));
    C8 = simplify(eq8 - subs(eq8, [dot_theta1, dot_theta2, dot_theta3, dot_theta4, dot_theta5, dot_theta6, dot_theta7, dot_theta8],[0,0,0,0,0,0,0,0]));
  
    Ceq11 = simplify(C1 - subs(C1, dot_theta1,0));
    Ceq12 = simplify(C1 - Ceq11 - subs(C1 - Ceq11, dot_theta2,0));
    Ceq13 = simplify(C1 - Ceq11 - Ceq12 - subs(C1 - Ceq11 - Ceq12 , dot_theta3,0));
    Ceq14 = simplify(C1 - Ceq11 - Ceq12 - Ceq13 - subs(C1 - Ceq11 - Ceq12 - Ceq13 , dot_theta4,0));
    Ceq15 = simplify(C1 - Ceq11 - Ceq12 - Ceq13 - Ceq14 - subs(C1 - Ceq11 - Ceq12 - Ceq13 - Ceq14 , dot_theta5,0));
    Ceq16 = simplify(C1 - Ceq11 - Ceq12 - Ceq13 - Ceq14 - Ceq15 - subs(C1 - Ceq11 - Ceq12 - Ceq13 - Ceq14 - Ceq15 , dot_theta6,0));
    Ceq17 = simplify(C1 - Ceq11 - Ceq12 - Ceq13 - Ceq14 - Ceq15 - Ceq16 - subs(C1 - Ceq11 - Ceq12 - Ceq13 - Ceq14 - Ceq15 - Ceq16 , dot_theta7,0));
    Ceq18 = simplify(C1 - Ceq11 - Ceq12 - Ceq13 - Ceq14 - Ceq15 - Ceq16 - Ceq17);
    
    Ceq21 = simplify(C2 - subs(C2, dot_theta1,0));
    Ceq22 = simplify(C2 - Ceq21 - subs(C2 - Ceq21, dot_theta2,0));
    Ceq23 = simplify(C2 - Ceq21 - Ceq22 - subs(C2 - Ceq21 - Ceq22 , dot_theta3,0));
    Ceq24 = simplify(C2 - Ceq21 - Ceq22 - Ceq23 - subs(C2 - Ceq21 - Ceq22 - Ceq23 , dot_theta4,0));
    Ceq25 = simplify(C2 - Ceq21 - Ceq22 - Ceq23 - Ceq24 - subs(C2 - Ceq21 - Ceq22 - Ceq23 - Ceq24 , dot_theta5,0));
    Ceq26 = simplify(C2 - Ceq21 - Ceq22 - Ceq23 - Ceq24 - Ceq25 - subs(C2 - Ceq21 - Ceq22 - Ceq23 - Ceq24 - Ceq25 , dot_theta6,0));
    Ceq27 = simplify(C2 - Ceq21 - Ceq22 - Ceq23 - Ceq24 - Ceq25 - Ceq26 - subs(C2 - Ceq21 - Ceq22 - Ceq23 - Ceq24 - Ceq25 - Ceq26 , dot_theta7,0));
    Ceq28 = simplify(C2 - Ceq21 - Ceq22 - Ceq23 - Ceq24 - Ceq25 - Ceq26 - Ceq27);
    
    Ceq31 = simplify(C3 - subs(C3, dot_theta1,0));
    Ceq32 = simplify(C3 - Ceq31 - subs(C3 - Ceq31, dot_theta2,0));
    Ceq33 = simplify(C3 - Ceq31 - Ceq32 - subs(C3 - Ceq31 - Ceq32 , dot_theta3,0));
    Ceq34 = simplify(C3 - Ceq31 - Ceq32 - Ceq33 - subs(C3 - Ceq31 - Ceq32 - Ceq33 , dot_theta4,0));
    Ceq35 = simplify(C3 - Ceq31 - Ceq32 - Ceq33 - Ceq34 - subs(C3 - Ceq31 - Ceq32 - Ceq33 - Ceq34 , dot_theta5,0));
    Ceq36 = simplify(C3 - Ceq31 - Ceq32 - Ceq33 - Ceq34 - Ceq35 - subs(C3 - Ceq31 - Ceq32 - Ceq33 - Ceq34 - Ceq35 , dot_theta6,0));
    Ceq37 = simplify(C3 - Ceq31 - Ceq32 - Ceq33 - Ceq34 - Ceq35 - Ceq36 - subs(C3 - Ceq31 - Ceq32 - Ceq33 - Ceq34 - Ceq35 - Ceq36 , dot_theta7,0));
    Ceq38 = simplify(C3 - Ceq31 - Ceq32 - Ceq33 - Ceq34 - Ceq35 - Ceq36 - Ceq37);
    
    Ceq41 = simplify(C4 - subs(C4, dot_theta1,0));
    Ceq42 = simplify(C4 - Ceq41 - subs(C4 - Ceq41, dot_theta2,0));
    Ceq43 = simplify(C4 - Ceq41 - Ceq42 - subs(C4 - Ceq41 - Ceq42 , dot_theta3,0));
    Ceq44 = simplify(C4 - Ceq41 - Ceq42 - Ceq43 - subs(C4 - Ceq41 - Ceq42 - Ceq43 , dot_theta4,0));
    Ceq45 = simplify(C4 - Ceq41 - Ceq42 - Ceq43 - Ceq44 - subs(C4 - Ceq41 - Ceq42 - Ceq43 - Ceq44 , dot_theta5,0));
    Ceq46 = simplify(C4 - Ceq41 - Ceq42 - Ceq43 - Ceq44 - Ceq45 - subs(C4 - Ceq41 - Ceq42 - Ceq43 - Ceq44 - Ceq45 , dot_theta6,0));
    Ceq47 = simplify(C4 - Ceq41 - Ceq42 - Ceq43 - Ceq44 - Ceq45 - Ceq46 - subs(C4 - Ceq41 - Ceq42 - Ceq43 - Ceq44 - Ceq45 - Ceq46 , dot_theta7,0));
    Ceq48 = simplify(C4 - Ceq41 - Ceq42 - Ceq43 - Ceq44 - Ceq45 - Ceq46 - Ceq47);

    Ceq51 = simplify(C5 - subs(C5, dot_theta1,0));
    Ceq52 = simplify(C5 - Ceq51 - subs(C5 - Ceq51, dot_theta2,0));
    Ceq53 = simplify(C5 - Ceq51 - Ceq52 - subs(C5 - Ceq51 - Ceq52 , dot_theta3,0));
    Ceq54 = simplify(C5 - Ceq51 - Ceq52 - Ceq53 - subs(C5 - Ceq51 - Ceq52 - Ceq53 , dot_theta4,0));
    Ceq55 = simplify(C5 - Ceq51 - Ceq52 - Ceq53 - Ceq54 - subs(C5 - Ceq51 - Ceq52 - Ceq53 - Ceq54 , dot_theta5,0));
    Ceq56 = simplify(C5 - Ceq51 - Ceq52 - Ceq53 - Ceq54 - Ceq55 - subs(C5 - Ceq51 - Ceq52 - Ceq53 - Ceq54 - Ceq55 , dot_theta6,0));
    Ceq57 = simplify(C5 - Ceq51 - Ceq52 - Ceq53 - Ceq54 - Ceq55 - Ceq56 - subs(C5 - Ceq51 - Ceq52 - Ceq53 - Ceq54 - Ceq55 - Ceq56 , dot_theta7,0));
    Ceq58 = simplify(C5 - Ceq51 - Ceq52 - Ceq53 - Ceq54 - Ceq55 - Ceq56 - Ceq57);
    
    Ceq61 = simplify(C6 - subs(C6, dot_theta1,0));
    Ceq62 = simplify(C6 - Ceq61 - subs(C6 - Ceq61, dot_theta2,0));
    Ceq63 = simplify(C6 - Ceq61 - Ceq62 - subs(C6 - Ceq61 - Ceq62 , dot_theta3,0));
    Ceq64 = simplify(C6 - Ceq61 - Ceq62 - Ceq63 - subs(C6 - Ceq61 - Ceq62 - Ceq63 , dot_theta4,0));
    Ceq65 = simplify(C6 - Ceq61 - Ceq62 - Ceq63 - Ceq64 - subs(C6 - Ceq61 - Ceq62 - Ceq63 - Ceq64 , dot_theta5,0));
    Ceq66 = simplify(C6 - Ceq61 - Ceq62 - Ceq63 - Ceq64 - Ceq65 - subs(C6 - Ceq61 - Ceq62 - Ceq63 - Ceq64 - Ceq65 , dot_theta6,0));
    Ceq67 = simplify(C6 - Ceq61 - Ceq62 - Ceq63 - Ceq64 - Ceq65 - Ceq66 - subs(C6 - Ceq61 - Ceq62 - Ceq63 - Ceq64 - Ceq65 - Ceq66 , dot_theta7,0));
    Ceq68 = simplify(C6 - Ceq61 - Ceq62 - Ceq63 - Ceq64 - Ceq65 - Ceq66 - Ceq67);
    
    Ceq71 = simplify(C7 - subs(C7, dot_theta1,0));
    Ceq72 = simplify(C7 - Ceq71 - subs(C7 - Ceq71, dot_theta2,0));
    Ceq73 = simplify(C7 - Ceq71 - Ceq72 - subs(C7 - Ceq71 - Ceq72 , dot_theta3,0));
    Ceq74 = simplify(C7 - Ceq71 - Ceq72 - Ceq73 - subs(C7 - Ceq71 - Ceq72 - Ceq73 , dot_theta4,0));
    Ceq75 = simplify(C7 - Ceq71 - Ceq72 - Ceq73 - Ceq74 - subs(C7 - Ceq71 - Ceq72 - Ceq73 - Ceq74 , dot_theta5,0));
    Ceq76 = simplify(C7 - Ceq71 - Ceq72 - Ceq73 - Ceq74 - Ceq75 - subs(C7 - Ceq71 - Ceq72 - Ceq73 - Ceq74 - Ceq75 , dot_theta6,0));
    Ceq77 = simplify(C7 - Ceq71 - Ceq72 - Ceq73 - Ceq74 - Ceq75 - Ceq76 - subs(C7 - Ceq71 - Ceq72 - Ceq73 - Ceq74 - Ceq75 - Ceq76 , dot_theta7,0));
    Ceq78 = simplify(C7 - Ceq71 - Ceq72 - Ceq73 - Ceq74 - Ceq75 - Ceq76 - Ceq77);
    
    Ceq81 = simplify(C8 - subs(C8, dot_theta1,0));
    Ceq82 = simplify(C8 - Ceq81 - subs(C8 - Ceq81, dot_theta2,0));
    Ceq83 = simplify(C8 - Ceq81 - Ceq82 - subs(C8 - Ceq81 - Ceq82 , dot_theta3,0));
    Ceq84 = simplify(C8 - Ceq81 - Ceq82 - Ceq83 - subs(C8 - Ceq81 - Ceq82 - Ceq83 , dot_theta4,0));
    Ceq85 = simplify(C8 - Ceq81 - Ceq82 - Ceq83 - Ceq84 - subs(C8 - Ceq81 - Ceq82 - Ceq83 - Ceq84 , dot_theta5,0));
    Ceq86 = simplify(C8 - Ceq81 - Ceq82 - Ceq83 - Ceq84 - Ceq85 - subs(C8 - Ceq81 - Ceq82 - Ceq83 - Ceq84 - Ceq85 , dot_theta6,0));
    Ceq87 = simplify(C8 - Ceq81 - Ceq82 - Ceq83 - Ceq84 - Ceq85 - Ceq86 - subs(C8 - Ceq81 - Ceq82 - Ceq83 - Ceq84 - Ceq85 - Ceq86 , dot_theta7,0));
    Ceq88 = simplify(C8 - Ceq81 - Ceq82 - Ceq83 - Ceq84 - Ceq85 - Ceq86 - Ceq87);
    disp('Dynamics:C, generating matrix...')
    C = [Ceq11/dot_theta1 Ceq12/dot_theta2 Ceq13/dot_theta3 Ceq14/dot_theta4 Ceq15/dot_theta5 Ceq16/dot_theta6 Ceq17/dot_theta7 Ceq18/dot_theta8;...
         Ceq21/dot_theta1 Ceq22/dot_theta2 Ceq23/dot_theta3 Ceq24/dot_theta4 Ceq25/dot_theta5 Ceq26/dot_theta6 Ceq27/dot_theta7 Ceq28/dot_theta8;...
         Ceq31/dot_theta1 Ceq32/dot_theta2 Ceq33/dot_theta3 Ceq34/dot_theta4 Ceq35/dot_theta5 Ceq36/dot_theta6 Ceq37/dot_theta7 Ceq38/dot_theta8;...
         Ceq41/dot_theta1 Ceq42/dot_theta2 Ceq43/dot_theta3 Ceq44/dot_theta4 Ceq45/dot_theta5 Ceq46/dot_theta6 Ceq47/dot_theta7 Ceq48/dot_theta8;...
         Ceq51/dot_theta1 Ceq52/dot_theta2 Ceq53/dot_theta3 Ceq54/dot_theta4 Ceq55/dot_theta5 Ceq56/dot_theta6 Ceq57/dot_theta7 Ceq58/dot_theta8;...
         Ceq61/dot_theta1 Ceq62/dot_theta2 Ceq63/dot_theta3 Ceq64/dot_theta4 Ceq65/dot_theta5 Ceq66/dot_theta6 Ceq67/dot_theta7 Ceq68/dot_theta8;...
         Ceq71/dot_theta1 Ceq72/dot_theta2 Ceq73/dot_theta3 Ceq74/dot_theta4 Ceq75/dot_theta5 Ceq76/dot_theta6 Ceq77/dot_theta7 Ceq78/dot_theta8;...
         Ceq81/dot_theta1 Ceq82/dot_theta2 Ceq83/dot_theta3 Ceq84/dot_theta4 Ceq85/dot_theta5 Ceq86/dot_theta6 Ceq87/dot_theta7 Ceq88/dot_theta8;...
         ] ;
     
    disp('Dynamics:C, simplifying matrix...')
    C = simplify(C);

    disp('Dynamics:G')
    Geq1 = subs(eq1,[ddot_theta1,ddot_theta2,ddot_theta3,ddot_theta4,ddot_theta5,ddot_theta6,ddot_theta7,ddot_theta8,dot_theta1,dot_theta2,dot_theta3,dot_theta4,dot_theta5,dot_theta6,dot_theta7,dot_theta8],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);
    Geq2 = subs(eq2,[ddot_theta1,ddot_theta2,ddot_theta3,ddot_theta4,ddot_theta5,ddot_theta6,ddot_theta7,ddot_theta8,dot_theta1,dot_theta2,dot_theta3,dot_theta4,dot_theta5,dot_theta6,dot_theta7,dot_theta8],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);
    Geq3 = subs(eq3,[ddot_theta1,ddot_theta2,ddot_theta3,ddot_theta4,ddot_theta5,ddot_theta6,ddot_theta7,ddot_theta8,dot_theta1,dot_theta2,dot_theta3,dot_theta4,dot_theta5,dot_theta6,dot_theta7,dot_theta8],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);
    Geq4 = subs(eq4,[ddot_theta1,ddot_theta2,ddot_theta3,ddot_theta4,ddot_theta5,ddot_theta6,ddot_theta7,ddot_theta8,dot_theta1,dot_theta2,dot_theta3,dot_theta4,dot_theta5,dot_theta6,dot_theta7,dot_theta8],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);
    Geq5 = subs(eq5,[ddot_theta1,ddot_theta2,ddot_theta3,ddot_theta4,ddot_theta5,ddot_theta6,ddot_theta7,ddot_theta8,dot_theta1,dot_theta2,dot_theta3,dot_theta4,dot_theta5,dot_theta6,dot_theta7,dot_theta8],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);
    Geq6 = subs(eq6,[ddot_theta1,ddot_theta2,ddot_theta3,ddot_theta4,ddot_theta5,ddot_theta6,ddot_theta7,ddot_theta8,dot_theta1,dot_theta2,dot_theta3,dot_theta4,dot_theta5,dot_theta6,dot_theta7,dot_theta8],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);
    Geq7 = subs(eq7,[ddot_theta1,ddot_theta2,ddot_theta3,ddot_theta4,ddot_theta5,ddot_theta6,ddot_theta7,ddot_theta8,dot_theta1,dot_theta2,dot_theta3,dot_theta4,dot_theta5,dot_theta6,dot_theta7,dot_theta8],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);
    Geq8 = subs(eq8,[ddot_theta1,ddot_theta2,ddot_theta3,ddot_theta4,ddot_theta5,ddot_theta6,ddot_theta7,ddot_theta8,dot_theta1,dot_theta2,dot_theta3,dot_theta4,dot_theta5,dot_theta6,dot_theta7,dot_theta8],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);

    G = [Geq1;Geq2;Geq3;Geq4;Geq5;Geq6;Geq7;Geq8];
    
    theta0abs = 0;
    theta1abs = theta1;
    theta2abs = theta1 + theta2;
    theta3abs = theta1 + theta2 + theta3;
    theta4abs = theta1 + theta2 + theta3 + theta4;
    theta5abs = theta1 + theta2 + theta3 + theta4 + theta5;
    theta6abs = theta1 + theta2 + theta3 + theta4 + theta5 + theta6;
    theta7abs = theta1 + theta2 + theta3 + theta4 + theta5 + theta6 + theta7;
    theta8abs = theta1 + theta2 + theta3 + theta4 + theta5 + theta6 + theta7 + theta8;

    theta18 = (theta8abs+theta7abs)/2;
    theta28 = (theta8abs+theta7abs)/2;
    
    cos18 = (cos(theta8abs-theta18));
    cos28 = (cos(theta8abs-theta28));
    sin18 = (sin(theta8abs-theta18));
    sin28 = (sin(theta8abs-theta28));
    
    theta17 = (theta7abs+theta6abs)/2;
    theta27 = (theta7abs+theta6abs)/2;
    
    cos17 = (cos(theta7abs-theta17)-cos(-theta7abs+theta18));
    cos27 = (cos(theta7abs-theta27)-cos(-theta7abs+theta28));
    sin17 = (sin(theta7abs-theta17)+sin(-theta7abs+theta18));
    sin27 = (sin(theta7abs-theta27)+sin(-theta7abs+theta28));

    theta16 = (theta6abs+theta5abs)/2;
    theta26 = (theta6abs+theta5abs)/2;
    
    cos16 = (cos(theta6abs-theta16)-cos(-theta6abs+theta17));
    cos26 = (cos(theta6abs-theta26)-cos(-theta6abs+theta27));
    sin16 = (sin(theta6abs-theta16)+sin(-theta6abs+theta17));
    sin26 = (sin(theta6abs-theta26)+sin(-theta6abs+theta27));
    
    theta15 = (theta5abs+theta4abs)/2;
    theta25 = (theta5abs+theta4abs)/2;
    
    cos15 = (cos(theta5abs-theta15)-cos(-theta5abs+theta16));
    cos25 = (cos(theta5abs-theta25)-cos(-theta5abs+theta26));
    sin15 = (sin(theta5abs-theta15)+sin(-theta5abs+theta16));
    sin25 = (sin(theta5abs-theta25)+sin(-theta5abs+theta26));
    
    theta14 = (theta3abs+theta4abs)/2;
    theta24 = (theta3abs+theta4abs)/2;
    
    cos14 = (cos(theta4abs - theta14)-cos(-theta4abs+theta15));
    cos24 = (cos(theta4abs - theta24)-cos(-theta4abs+theta25));
    sin14 = (sin(theta4abs - theta14)+sin(-theta4abs+theta15));
    sin24 = (sin(theta4abs - theta24)+sin(-theta4abs+theta25));
    
    theta13 = (theta3abs+theta2abs)/2;
    theta23 = (theta3abs+theta2abs)/2;  
    
    cos13 = (cos(theta3abs-theta13)-cos(-theta3abs+theta14));
    cos23 = (cos(theta3abs-theta23)-cos(-theta3abs+theta24));
    sin13 = (sin(theta3abs-theta13)+sin(-theta3abs+theta14));
    sin23 = (sin(theta3abs-theta23)+sin(-theta3abs+theta24));
    
    %theta12 = atan( ( r*(cos(theta2abs)-cos(theta1abs)) +l*(sin(theta2abs)+sin(theta1abs)) ) /  ( r*(sin(theta1abs)-sin(theta2abs)) +l*(cos(theta2abs)+cos(theta1abs)))     );
    %theta22 = atan( ( r*(-cos(theta2abs)+cos(theta1abs)) +l*(sin(theta2abs)+sin(theta1abs)) ) /  ( r*(-sin(theta1abs)+sin(theta2abs)) +l*(cos(theta2abs)+cos(theta1abs)))     );
    theta12 = (theta1abs+theta2abs)/2;
    theta22 = (theta1abs+theta2abs)/2;      
    
    cos12 = (cos(theta2abs-theta12)-cos(-theta2abs+theta13));
    cos22 = (cos(theta2abs-theta22)-cos(-theta2abs+theta23));
    sin12 = (sin(theta2abs-theta12)+sin(-theta2abs+theta13));
    sin22 = (sin(theta2abs-theta22)+sin(-theta2abs+theta23));
    
    %theta11 = atan( ( r*(cos(theta1abs)-cos(theta0abs)) +l*(sin(theta1abs)+sin(theta0abs)) ) /  ( r*(sin(theta0abs)-sin(theta1abs)) +l*(cos(theta1abs)+cos(theta0abs)))     );
    %theta21 = atan( ( r*(-cos(theta1abs)+cos(theta0abs)) +l*(sin(theta1abs)+sin(theta0abs)) ) /  ( r*(-sin(theta0abs)+sin(theta1abs)) +l*(cos(theta1abs)+cos(theta0abs)))     );
    theta11 = (theta1abs+theta0abs)/2;
    theta21 = (theta1abs+theta0abs)/2;       
    
    cos11 = (cos(theta1abs-theta11)-cos(-theta1abs+theta12));
    cos21 = (cos(theta1abs-theta21)-cos(-theta1abs+theta22));
    sin11 = (sin(theta1abs-theta11)+sin(-theta1abs+theta12));
    sin21 = (sin(theta1abs-theta21)+sin(-theta1abs+theta22));
    disp('Dynamics:wd')   
    
    wd1 = [(-2*(f1*cos11+f2*cos21)*l*(0                                                     +           0                                   +        0                                  + 0                               + 0                         + 0                  + 0          ) +(f1*cos11-f2*cos21)*r  +(f1*sin11+f2*sin21)*l*(1 + 0             + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
            0;
            0;
            0;
            0;
            0;
            0;
            0];
     
    wd2 = [(-2*(f1*cos12+f2*cos22)*l*(sin(theta2)                                           +           0                                   +        0                                  + 0                               + 0                         + 0                  + 0          ) +(f1*cos12-f2*cos22)*r  +(f1*sin12+f2*sin22)*l*(1 + 2*cos(theta2) + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos12+f2*cos22)*l*(0                                                     +           0                                   +        0                                  + 0                               + 0                         + 0                  + 0          ) +(f1*cos12-f2*cos22)*r  +(f1*sin12+f2*sin22)*l*(1 + 0             + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           0;
           0;
           0;
           0;
           0;
           0];
       
    wd3 = [(-2*(f1*cos13+f2*cos23)*l*(sin(theta2+theta3)                                    + sin(theta3)                                   +        0                                  + 0                               + 0                         + 0                  + 0          ) +(f1*cos13-f2*cos23)*r  +(f1*sin13+f2*sin23)*l*(1 + 2*cos(theta3) + 2*cos(theta2+theta3) + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos13+f2*cos23)*l*(0                                                     + sin(theta3)                                   +        0                                  + 0                               + 0                         + 0                  + 0          ) +(f1*cos13-f2*cos23)*r  +(f1*sin13+f2*sin23)*l*(1 + 2*cos(theta3) + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos13+f2*cos23)*l*(0                                                     +           0                                   +        0                                  + 0                               + 0                         + 0                  + 0          ) +(f1*cos13-f2*cos23)*r  +(f1*sin13+f2*sin23)*l*(1 + 0             + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
            0;
            0;
            0;
            0;
            0];
        
    wd4 = [(-2*(f1*cos14+f2*cos24)*l*(sin(theta2+theta3+theta4)                             + sin(theta3+theta4)                            + sin(theta4)                               + 0                               + 0                         + 0                  + 0          ) +(f1*cos14-f2*cos24)*r  +(f1*sin14+f2*sin24)*l*(1 + 2*cos(theta4) + 2*cos(theta3+theta4) + 2*cos(theta2+theta3+theta4) + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos14+f2*cos24)*l*(                               0                      + sin(theta3+theta4)                            + sin(theta4)                               + 0                               + 0                         + 0                  + 0          ) +(f1*cos14-f2*cos24)*r  +(f1*sin14+f2*sin24)*l*(1 + 2*cos(theta4) + 2*cos(theta3+theta4) + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos14+f2*cos24)*l*(                               0                      +                  0                            + sin(theta4)                               + 0                               + 0                         + 0                  + 0          ) +(f1*cos14-f2*cos24)*r  +(f1*sin14+f2*sin24)*l*(1 + 2*cos(theta4) + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos14+f2*cos24)*l*(                               0                      +                  0                            + 0                                         + 0                               + 0                         + 0                  + 0          ) +(f1*cos14-f2*cos24)*r  +(f1*sin14+f2*sin24)*l*(1 + 0             + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           0;
           0;
           0;
           0];

    wd5 = [(-2*(f1*cos15+f2*cos25)*l*(sin(theta2+theta3+theta4+theta5)                      + sin(theta3+theta4+theta5)                     + sin(theta4+theta5)                        + sin(theta5)                     + 0                         + 0                  + 0          ) +(f1*cos15-f2*cos25)*r  +(f1*sin15+f2*sin25)*l*(1 + 2*cos(theta5) + 2*cos(theta4+theta5) + 2*cos(theta3+theta4+theta5) + 2*cos(theta2+theta3+theta4+theta5) + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos15+f2*cos25)*l*(                               0                      + sin(theta3+theta4+theta5)                     + sin(theta4+theta5)                        + sin(theta5)                     + 0                         + 0                  + 0          ) +(f1*cos15-f2*cos25)*r  +(f1*sin15+f2*sin25)*l*(1 + 2*cos(theta5) + 2*cos(theta4+theta5) + 2*cos(theta3+theta4+theta5) + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos15+f2*cos25)*l*(                               0                      +                         0                     + sin(theta4+theta5)                        + sin(theta5)                     + 0                         + 0                  + 0          ) +(f1*cos15-f2*cos25)*r  +(f1*sin15+f2*sin25)*l*(1 + 2*cos(theta5) + 2*cos(theta4+theta5) + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos15+f2*cos25)*l*(                               0                      +                         0                     + 0                                         + sin(theta5)                     + 0                         + 0                  + 0          ) +(f1*cos15-f2*cos25)*r  +(f1*sin15+f2*sin25)*l*(1 + 2*cos(theta5) + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos15+f2*cos25)*l*(                               0                      +                         0                     + 0                                         + 0                               + 0                         + 0                  + 0          ) +(f1*cos15-f2*cos25)*r  +(f1*sin15+f2*sin25)*l*(1 + 0             + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           0;
           0;
           0];
 
    wd6 = [(-2*(f1*cos16+f2*cos26)*l*(sin(theta2+theta3+theta4+theta5+theta6)               + sin(theta3+theta4+theta5+theta6)              + sin(theta4+theta5+theta6)                 + sin(theta5+theta6)              + sin(theta6)               + 0                  + 0          ) +(f1*cos16-f2*cos26)*r  +(f1*sin16+f2*sin26)*l*(1 + 2*cos(theta6) + 2*cos(theta5+theta6) + 2*cos(theta4+theta5+theta6) + 2*cos(theta3+theta4+theta5+theta6) + 2*cos(theta2+theta3+theta4+theta5+theta6) + 0                                                + 0                                                        )   );...
           (-2*(f1*cos16+f2*cos26)*l*(                               0                      + sin(theta3+theta4+theta5+theta6)              + sin(theta4+theta5+theta6)                 + sin(theta5+theta6)              + sin(theta6)               + 0                  + 0          ) +(f1*cos16-f2*cos26)*r  +(f1*sin16+f2*sin26)*l*(1 + 2*cos(theta6) + 2*cos(theta5+theta6) + 2*cos(theta4+theta5+theta6) + 2*cos(theta3+theta4+theta5+theta6) + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos16+f2*cos26)*l*(                               0                      +                                0              + sin(theta4+theta5+theta6)                 + sin(theta5+theta6)              + sin(theta6)               + 0                  + 0          ) +(f1*cos16-f2*cos26)*r  +(f1*sin16+f2*sin26)*l*(1 + 2*cos(theta6) + 2*cos(theta5+theta6) + 2*cos(theta4+theta5+theta6) + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos16+f2*cos26)*l*(                               0                      +                                0              + 0                                         + sin(theta5+theta6)              + sin(theta6)               + 0                  + 0          ) +(f1*cos16-f2*cos26)*r  +(f1*sin16+f2*sin26)*l*(1 + 2*cos(theta6) + 2*cos(theta5+theta6) + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos16+f2*cos26)*l*(                               0                      +                                0              + 0                                         + 0                               + sin(theta6)               + 0                  + 0          ) +(f1*cos16-f2*cos26)*r  +(f1*sin16+f2*sin26)*l*(1 + 2*cos(theta6) + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos16+f2*cos26)*l*(                               0                      +                                0              + 0                                         + 0                               + 0                         + 0                  + 0          ) +(f1*cos16-f2*cos26)*r  +(f1*sin16+f2*sin26)*l*(1 + 0             + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           0;
           0];
    
    wd7 = [(-2*(f1*cos17+f2*cos27)*l*(sin(theta2+theta3+theta4+theta5+theta6+theta7)        + sin(theta3+theta4+theta5+theta6+theta7)       + sin(theta4+theta5+theta6+theta7)         + sin(theta5+theta6+theta7)        + sin(theta6+theta7)        + sin(theta7)        + 0          ) +(f1*cos17-f2*cos27)*r  +(f1*sin17+f2*sin27)*l*(1 + 2*cos(theta7) + 2*cos(theta6+theta7) + 2*cos(theta5+theta6+theta7) + 2*cos(theta4+theta5+theta6+theta7) + 2*cos(theta3+theta4+theta5+theta6+theta7) + 2*cos(theta2+theta3+theta4+theta5+theta6+theta7) + 0                                                        )   );...
           (-2*(f1*cos17+f2*cos27)*l*(                               0                      + sin(theta3+theta4+theta5+theta6+theta7)       + sin(theta4+theta5+theta6+theta7)         + sin(theta5+theta6+theta7)        + sin(theta6+theta7)        + sin(theta7)        + 0          ) +(f1*cos17-f2*cos27)*r  +(f1*sin17+f2*sin27)*l*(1 + 2*cos(theta7) + 2*cos(theta6+theta7) + 2*cos(theta5+theta6+theta7) + 2*cos(theta4+theta5+theta6+theta7) + 2*cos(theta3+theta4+theta5+theta6+theta7) + 0                                                + 0                                                        )   );...
           (-2*(f1*cos17+f2*cos27)*l*(                               0                      +                                0              + sin(theta4+theta5+theta6+theta7)         + sin(theta5+theta6+theta7)        + sin(theta6+theta7)        + sin(theta7)        + 0          ) +(f1*cos17-f2*cos27)*r  +(f1*sin17+f2*sin27)*l*(1 + 2*cos(theta7) + 2*cos(theta6+theta7) + 2*cos(theta5+theta6+theta7) + 2*cos(theta4+theta5+theta6+theta7) + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos17+f2*cos27)*l*(                               0                      +                                0              + 0                                        + sin(theta5+theta6+theta7)        + sin(theta6+theta7)        + sin(theta7)        + 0          ) +(f1*cos17-f2*cos27)*r  +(f1*sin17+f2*sin27)*l*(1 + 2*cos(theta7) + 2*cos(theta6+theta7) + 2*cos(theta5+theta6+theta7) + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos17+f2*cos27)*l*(                               0                      +                                0              + 0                                        + 0                                + sin(theta6+theta7)        + sin(theta7)        + 0          ) +(f1*cos17-f2*cos27)*r  +(f1*sin17+f2*sin27)*l*(1 + 2*cos(theta7) + 2*cos(theta6+theta7) + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos17+f2*cos27)*l*(                               0                      +                                0              + 0                                        + 0                                + 0                         + sin(theta7)        + 0          ) +(f1*cos17-f2*cos27)*r  +(f1*sin17+f2*sin27)*l*(1 + 2*cos(theta7) + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos17+f2*cos27)*l*(                               0                      +                                0              + 0                                        + 0                                + 0                         + 0                  + 0          ) +(f1*cos17-f2*cos27)*r  +(f1*sin17+f2*sin27)*l*(1 + 0             + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           0];
           
    wd8 = [(-2*(f1*cos18+f2*cos28)*l*(sin(theta2+theta3+theta4+theta5+theta6+theta7+theta8) + sin(theta3+theta4+theta5+theta6+theta7+theta8) + sin(theta4+theta5+theta6+theta7+theta8) + sin(theta5+theta6+theta7+theta8) + sin(theta6+theta7+theta8) + sin(theta7+theta8) + sin(theta8)) +(f1*cos18-f2*cos28)*r  +(f1*sin18+f2*sin28)*l*(1 + 2*cos(theta8) + 2*cos(theta7+theta8) + 2*cos(theta6+theta7+theta8) + 2*cos(theta5+theta6+theta7+theta8) + 2*cos(theta4+theta5+theta6+theta7+theta8) + 2*cos(theta3+theta4+theta5+theta6+theta7+theta8) + 2*cos(theta2+theta3+theta4+theta5+theta6+theta7+theta8)  )   );...
           (-2*(f1*cos18+f2*cos28)*l*(                               0                      + sin(theta3+theta4+theta5+theta6+theta7+theta8) + sin(theta4+theta5+theta6+theta7+theta8) + sin(theta5+theta6+theta7+theta8) + sin(theta6+theta7+theta8) + sin(theta7+theta8) + sin(theta8)) +(f1*cos18-f2*cos28)*r  +(f1*sin18+f2*sin28)*l*(1 + 2*cos(theta8) + 2*cos(theta7+theta8) + 2*cos(theta6+theta7+theta8) + 2*cos(theta5+theta6+theta7+theta8) + 2*cos(theta4+theta5+theta6+theta7+theta8) + 2*cos(theta3+theta4+theta5+theta6+theta7+theta8) + 0                                                        )   );...
           (-2*(f1*cos18+f2*cos28)*l*(                               0                      +                                              0 + sin(theta4+theta5+theta6+theta7+theta8) + sin(theta5+theta6+theta7+theta8) + sin(theta6+theta7+theta8) + sin(theta7+theta8) + sin(theta8)) +(f1*cos18-f2*cos28)*r  +(f1*sin18+f2*sin28)*l*(1 + 2*cos(theta8) + 2*cos(theta7+theta8) + 2*cos(theta6+theta7+theta8) + 2*cos(theta5+theta6+theta7+theta8) + 2*cos(theta4+theta5+theta6+theta7+theta8) + 0                                                + 0                                                        )   );...
           (-2*(f1*cos18+f2*cos28)*l*(                               0                      +                                              0 + 0                                       + sin(theta5+theta6+theta7+theta8) + sin(theta6+theta7+theta8) + sin(theta7+theta8) + sin(theta8)) +(f1*cos18-f2*cos28)*r  +(f1*sin18+f2*sin28)*l*(1 + 2*cos(theta8) + 2*cos(theta7+theta8) + 2*cos(theta6+theta7+theta8) + 2*cos(theta5+theta6+theta7+theta8) + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos18+f2*cos28)*l*(                               0                      +                                              0 + 0                                       + 0                                + sin(theta6+theta7+theta8) + sin(theta7+theta8) + sin(theta8)) +(f1*cos18-f2*cos28)*r  +(f1*sin18+f2*sin28)*l*(1 + 2*cos(theta8) + 2*cos(theta7+theta8) + 2*cos(theta6+theta7+theta8) + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos18+f2*cos28)*l*(                               0                      +                                              0 + 0                                       + 0                                + 0                         + sin(theta7+theta8) + sin(theta8)) +(f1*cos18-f2*cos28)*r  +(f1*sin18+f2*sin28)*l*(1 + 2*cos(theta8) + 2*cos(theta7+theta8) + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos18+f2*cos28)*l*(                               0                      +                                              0 + 0                                       + 0                                + 0                         + 0                  + sin(theta8)) +(f1*cos18-f2*cos28)*r  +(f1*sin18+f2*sin28)*l*(1 + 2*cos(theta8) + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   );...
           (-2*(f1*cos18+f2*cos28)*l*(                               0                      +                                              0 + 0                                       + 0                                + 0                         + 0                  + 0          ) +(f1*cos18-f2*cos28)*r  +(f1*sin18+f2*sin28)*l*(1 + 0             + 0                    + 0                           + 0                                  + 0                                         + 0                                                + 0                                                        )   )];


       
       
    disp('Dynamics:Q')   
    Q = wd1+wd2+wd3+wd4+wd5+wd6+wd7+wd8;
    
end